project:
  type: default
  output-dir: rapport

title: "Prédiction de la Satisfaction Client pour les Parfums"
subtitle: "Compléments de Mathématiques 2 -- Introduction au Machine Learning"
author: "HAMLIL Mohamed"
date: "2025-01-15"
lang: fr

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: custom.css
    include-after-body: pdf-link.html
    format-links: false
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    embed-resources: true
    highlight-style: github
    date-format: "YYYY"
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    fig-cap-location: bottom
    date-format: "x"
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhead[RO]{HAMLIL Mohamed}
          \fancyhead[LO]{Compléments de Mathématiques 2 L3 MIASHS}
          \usepackage{float}
          \usepackage{booktabs}
          \floatplacement{figure}{H}
          \usepackage[most]{tcolorbox}

execute:
  warning: false
  message: false
  fig-align: center
  fig-width: 7
  fig-height: 5

bibliography: references.bib
