project:
  type: default

lang: fr

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: custom.css
    include-after-body: pdf-link.html
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    embed-resources: true
    highlight-style: github
    date-format: "YYYY"

execute:
  warning: false
  message: false
  fig-align: center
