project:
  type: default

lang: fr

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: custom.css
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    embed-resources: true
    highlight-style: github
    date-format: "YYYY"
  pdf:
    toc: true

execute:
  warning: false
  message: false
